server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "password"
    sources:
      youtube: true
      soundcloud: true
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

metrics:
  prometheus:
    enabled: false
